name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  date_today:
    runs-on: ubuntu-24.04
    steps:
      - name: Now it is
        run : | 
          date