name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env:
  SHOULD_DEPLOY: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Trigger deployment
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4 
      - name: Bump version and push tag
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  discord_notification:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-24.04
    steps:
      - name: Deployment success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: A new version of Pokedex deployed
          webhookUrl: https://study.cs.helsinki.fi/discord/webhooks/1264842173619109949
      - name: Build failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build failed
          webhookUrl: https://study.cs.helsinki.fi/discord/webhooks/1264842173619109949
      - name: Build canceled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Build canceled
          webhookUrl: https://study.cs.helsinki.fi/discord/webhooks/1264842173619109949
  